$(warning USE_PREBUILT_KERNEL is enabled: using kernel prebuilts from device/oneplus/macanc-kernel)

TARGET_NO_KERNEL_OVERRIDE := true
KERNEL_PREBUILT_PATH := device/oneplus/macanc-kernel
BOARD_PREBUILT_DTBIMAGE_DIR := $(KERNEL_PREBUILT_PATH)/images/
BOARD_PREBUILT_DTBOIMAGE := $(KERNEL_PREBUILT_PATH)/images/dtbo.img
PRODUCT_COPY_FILES += \
	$(KERNEL_PREBUILT_PATH)/images/kernel:kernel

# Kernel modules
SYSTEMDLKM_MODULES_PATH := $(KERNEL_PREBUILT_PATH)/modules/system_dlkm
VENDORDLKM_MODULES_PATH := $(KERNEL_PREBUILT_PATH)/modules/vendor_dlkm
RAMDISK_MODULES_PATH := $(KERNEL_PREBUILT_PATH)/modules/vendor_ramdisk

BOARD_SYSTEM_KERNEL_MODULES := $(wildcard $(SYSTEMDLKM_MODULES_PATH)/*.ko)
BOARD_SYSTEM_KERNEL_MODULES_LOAD := $(patsubst %,$(SYSTEMDLKM_MODULES_PATH)/%,$(shell cat $(SYSTEMDLKM_MODULES_PATH)/modules.load))

BOARD_VENDOR_KERNEL_MODULES := $(wildcard $(VENDORDLKM_MODULES_PATH)/*.ko)
BOARD_VENDOR_KERNEL_MODULES_LOAD := $(patsubst %,$(VENDORDLKM_MODULES_PATH)/%,$(shell cat $(VENDORDLKM_MODULES_PATH)/modules.load))
BOARD_VENDOR_KERNEL_MODULES_BLOCKLIST_FILE := $(VENDORDLKM_MODULES_PATH)/modules.blocklist

BOARD_VENDOR_RAMDISK_KERNEL_MODULES := $(wildcard $(RAMDISK_MODULES_PATH)/*.ko)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(patsubst %,$(RAMDISK_MODULES_PATH)/%,$(shell cat $(RAMDISK_MODULES_PATH)/modules.load))
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD  := $(patsubst %,$(RAMDISK_MODULES_PATH)/%,$(shell cat $(RAMDISK_MODULES_PATH)/modules.load.recovery))
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_BLOCKLIST_FILE := $(RAMDISK_MODULES_PATH)/modules.blocklist

SYSTEM_KERNEL_MODULES := $(BOARD_SYSTEM_KERNEL_MODULES_LOAD)
BOOT_KERNEL_MODULES := $(BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD)
